# Build-Stage
FROM node:18-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production-Stage
FROM nginx:alpine

# Nginx Konfiguration kopieren
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Build-Dateien kopieren
COPY --from=builder /app/dist /usr/share/nginx/html

# Port 80 exposieren
EXPOSE 80

# Nginx starten
CMD ["nginx", "-g", "daemon off;"]