version: '3.8'

services:
  frontend:
    image: image-gallery-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "9080:80"
    networks:
      - image-gallery-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - frontend_node_modules:/app/node_modules

  backend:
    image: image-gallery-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - "4000"
    networks:
      - image-gallery-network
    environment:
      - DATABASE_URL=postgresql://user:${DB_PASSWORD}@db:5432/imagegallery
      - NODE_ENV=production
      - MAX_FILE_SIZE=10485760
      - UPLOAD_PATH=/app/uploads
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ${UPLOAD_PATH}:/app/uploads
      - backend_node_modules:/app/node_modules

  db:
    image: postgres:14-alpine
    expose:
      - "5432"
    networks:
      - image-gallery-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=imagegallery
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  image-gallery-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  frontend_node_modules:
    driver: local
  backend_node_modules:
    driver: local