version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "9080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/imagegallery
      - NODE_ENV=production
      - MAX_FILE_SIZE=10485760
      - UPLOAD_PATH=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=imagegallery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: